### ISSUE TITLE
Library Issue

### ISSUE THREAD

**Issue by Shrey7801** [HeeebsInc/NN_Weapon_Detection#2]
I am getting error for PyFunctions library.
No module named PyFunctions

**Comment by HeeebsInc** [comment]
The PyFunctions directory is [here](https://github.com/HeeebsInc/WeaponDetection/tree/master/PyFunctions).  If you are having trouble accessing it try adding the folder to your path

**Comment by Shrey7801** [comment]
How can I do it ?
Can you please explain me the steps?
from PyFunctions import functions as func
from PyFunctions import var 
These two commands are getting error.

**Comment by HeeebsInc** [comment]
In order to import from that directory there are two options

@Mafia7801 
1) Add the directory to the import path using `sys`
2) Move the PyFunctions directory into the same location where the script you are trying to run is located. 


Can you provide a screenshot of your directory structure? 

If you are using Linux - run `apt-get update && apt-get install tree` 
then please `cd` into the project directory and type `tree` and send a link to the screen shot
